
package com.amazonaws.mws.model.orders;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://mws.amazonservices.com/Orders/2011-01-01}ListOrdersByNextTokenResult"/>
 *         &lt;element ref="{https://mws.amazonservices.com/Orders/2011-01-01}ResponseMetadata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Sun Feb 06 00:05:50 UTC 2011
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listOrdersByNextTokenResult",
    "responseMetadata"
})
@XmlRootElement(name = "ListOrdersByNextTokenResponse")
public class ListOrdersByNextTokenResponse {

    @XmlElement(name = "ListOrdersByNextTokenResult", required = true)
    protected ListOrdersByNextTokenResult listOrdersByNextTokenResult;
    @XmlElement(name = "ResponseMetadata", required = true)
    protected ResponseMetadata responseMetadata;

    /**
     * Default constructor
     * 
     */
    public ListOrdersByNextTokenResponse() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public ListOrdersByNextTokenResponse(final ListOrdersByNextTokenResult listOrdersByNextTokenResult, final ResponseMetadata responseMetadata) {
        this.listOrdersByNextTokenResult = listOrdersByNextTokenResult;
        this.responseMetadata = responseMetadata;
    }

    /**
     * Gets the value of the listOrdersByNextTokenResult property.
     * 
     * @return
     *     possible object is
     *     {@link ListOrdersByNextTokenResult }
     *     
     */
    public ListOrdersByNextTokenResult getListOrdersByNextTokenResult() {
        return listOrdersByNextTokenResult;
    }

    /**
     * Sets the value of the listOrdersByNextTokenResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOrdersByNextTokenResult }
     *     
     */
    public void setListOrdersByNextTokenResult(ListOrdersByNextTokenResult value) {
        this.listOrdersByNextTokenResult = value;
    }

    public boolean isSetListOrdersByNextTokenResult() {
        return (this.listOrdersByNextTokenResult!= null);
    }

    /**
     * Gets the value of the responseMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMetadata }
     *     
     */
    public ResponseMetadata getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Sets the value of the responseMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMetadata }
     *     
     */
    public void setResponseMetadata(ResponseMetadata value) {
        this.responseMetadata = value;
    }

    public boolean isSetResponseMetadata() {
        return (this.responseMetadata!= null);
    }

    /**
     * Sets the value of the ListOrdersByNextTokenResult property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListOrdersByNextTokenResponse withListOrdersByNextTokenResult(ListOrdersByNextTokenResult value) {
        setListOrdersByNextTokenResult(value);
        return this;
    }

    /**
     * Sets the value of the ResponseMetadata property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public ListOrdersByNextTokenResponse withResponseMetadata(ResponseMetadata value) {
        setResponseMetadata(value);
        return this;
    }
    

    /**
     * 
     * XML string representation of this object
     * 
     * @return XML String
     */
    public String toXML() {
        StringBuffer xml = new StringBuffer();
        xml.append("<ListOrdersByNextTokenResponse xmlns=\"https://mws.amazonservices.com/Orders/2011-01-01\">");
        if (isSetListOrdersByNextTokenResult()) {
            ListOrdersByNextTokenResult  listOrdersByNextTokenResult = getListOrdersByNextTokenResult();
            xml.append("<ListOrdersByNextTokenResult>");
            xml.append(listOrdersByNextTokenResult.toXMLFragment());
            xml.append("</ListOrdersByNextTokenResult>");
        } 
        if (isSetResponseMetadata()) {
            ResponseMetadata  responseMetadata = getResponseMetadata();
            xml.append("<ResponseMetadata>");
            xml.append(responseMetadata.toXMLFragment());
            xml.append("</ResponseMetadata>");
        } 
        xml.append("</ListOrdersByNextTokenResponse>");
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     * 
     * JSON string representation of this object
     * 
     * @return JSON String
     */
    public String toJSON() {
        StringBuffer json = new StringBuffer();
        json.append("{\"ListOrdersByNextTokenResponse\" : {");
        json.append(quoteJSON("@xmlns"));
        json.append(" : ");
        json.append(quoteJSON("https://mws.amazonservices.com/Orders/2011-01-01"));
        boolean first = true;
        json.append(", ");
        if (isSetListOrdersByNextTokenResult()) {
            if (!first) json.append(", ");
            json.append("\"ListOrdersByNextTokenResult\" : {");
            ListOrdersByNextTokenResult  listOrdersByNextTokenResult = getListOrdersByNextTokenResult();

            json.append(listOrdersByNextTokenResult.toJSONFragment());
            json.append("}");
            first = false;
        } 
        if (isSetResponseMetadata()) {
            if (!first) json.append(", ");
            json.append("\"ResponseMetadata\" : {");
            ResponseMetadata  responseMetadata = getResponseMetadata();

            json.append(responseMetadata.toJSONFragment());
            json.append("}");
            first = false;
        } 
        json.append("}");
        json.append("}");
        return json.toString();
    }

    /**
     * 
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
                }
            }
        }
        sb.append("\"");
        return sb.toString();
    }


}
